/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package email_client;

import email_client.global.GithubProfile;
import email_client.global.IconImageUtilities;
import email_client.global.LookandFeel;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author notmiyouji
 */
public class anotherAboutTeam extends javax.swing.JFrame {
    
    GithubProfile profileLink = new GithubProfile();
    
    /**
     * Creates new form anotherAboutTeam
     */
    public anotherAboutTeam() {
        initComponents();
        IconImageUtilities.setIconImage(this);
        firstGithub.setText("<html> <a href=\"\">"+ profileLink.getTwodgirlsismywaifu() +"</a></html>");
        secondGithub.setText("<html> <a href=\"\">"+ profileLink.getPhoebeHa0320() +"</a></html>");
        thirdGithub.setText("<html> <a href=\"\">"+ profileLink.getNgohien0810() +"</a></html>");
        fourthGithub.setText("<html> <a href=\"\">"+ profileLink.getLedat220497() +"</a></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new email_client.global.ImageAvatar();
        imageAvatar2 = new email_client.global.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstGithub = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondGithub = new javax.swing.JLabel();
        imageAvatar3 = new email_client.global.ImageAvatar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thirdGithub = new javax.swing.JLabel();
        imageAvatar4 = new email_client.global.ImageAvatar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fourthGithub = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin nhóm");
        setBackground(new java.awt.Color(255, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/90584137.jpg"))); // NOI18N
        getContentPane().add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 276, 128, 128));

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/59259855.jpg"))); // NOI18N
        getContentPane().add(imageAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, 128, 128));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ngô Thành Long");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 86, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Email: ngothanhlong19943@gmail.com");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 154, 260, -1));

        firstGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstGithub.setText("github");
        firstGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstGithubMouseClicked(evt);
            }
        });
        getContentPane().add(firstGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 188, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nguyễn Ngọc Hoàng Hà");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 276, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Email: hoangha2000@gmail.com");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 344, 260, -1));

        secondGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        secondGithub.setText("github");
        secondGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondGithubMouseClicked(evt);
            }
        });
        getContentPane().add(secondGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 378, -1, -1));

        imageAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/47359493.jpg"))); // NOI18N
        getContentPane().add(imageAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 86, 128, 128));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Ngô Thị Hiền");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 86, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Email: example@domain.com");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 154, 260, -1));

        thirdGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        thirdGithub.setText("github");
        thirdGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdGithubMouseClicked(evt);
            }
        });
        getContentPane().add(thirdGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 188, -1, -1));

        imageAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/70122193.jpg"))); // NOI18N
        getContentPane().add(imageAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 276, 128, 128));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Lê Tiến Đạtl");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 276, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Email: example@domain.com");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 344, 260, -1));

        fourthGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fourthGithub.setText("github");
        fourthGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourthGithubMouseClicked(evt);
            }
        });
        getContentPane().add(fourthGithub, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 378, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nhóm 7: Email Client Manager - Quản lý Email người dùng");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 853, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("@2dgirlismywaifu");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("@PhoebeHa0320");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("@ngohien0810");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("@ledat220497");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        jLabel14.setBackground(new java.awt.Color(234, 247, 247));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 890, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstGithubMouseClicked
        // TODO add your handling code here:
        firstGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getTwodgirlsismywaifu());
    }//GEN-LAST:event_firstGithubMouseClicked

    private void secondGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondGithubMouseClicked
        // TODO add your handling code here:
        secondGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getPhoebeHa0320());
    }//GEN-LAST:event_secondGithubMouseClicked

    private void thirdGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdGithubMouseClicked
        // TODO add your handling code here:
        thirdGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getNgohien0810());
    }//GEN-LAST:event_thirdGithubMouseClicked

    private void fourthGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthGithubMouseClicked
        // TODO add your handling code here:
        fourthGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getLedat220497());
    }//GEN-LAST:event_fourthGithubMouseClicked
    
    private void goToProfile(String url) {
        try {
            Desktop.getDesktop().browse(new URI(url));
        } catch (URISyntaxException | IOException ex) {
                ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        LookandFeel.setTheme();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new anotherAboutTeam().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstGithub;
    private javax.swing.JLabel fourthGithub;
    private email_client.global.ImageAvatar imageAvatar1;
    private email_client.global.ImageAvatar imageAvatar2;
    private email_client.global.ImageAvatar imageAvatar3;
    private email_client.global.ImageAvatar imageAvatar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel secondGithub;
    private javax.swing.JLabel thirdGithub;
    // End of variables declaration//GEN-END:variables
}
