/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package email_client;

import email_client.callFrame.frameAddAccount;
import email_client.callFrame.frameManageAccount;
import email_client.callFrame.frameSendEmail;
import email_client.global.LookandFeel;
import email_client.global.IconImageUtilities;
import email_client.dialogMess.NetworkNotify;
import email_client.sqlitehelper.sqlitehelper;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author notmiyouji
 */
public class HomePage extends javax.swing.JFrame {
    
    Connection connection = sqlitehelper.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    
    
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        loaddatabase();
        //icon mặc định của phần mềm
        IconImageUtilities.setIconImage(this);
        //load danh sách email
        loadEmailList();
        //mặc định tạm tắt chức năng trừ thêm tài khoản, thông tin về phần mềm
        disableFunction();
    }
    
    public final void loaddatabase() {
        try {
            Statement statement = connection.createStatement();
            statement.setQueryTimeout(30);  // set timeout to 30 sec          
            statement.executeUpdate("create table email (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "
                    + "name TEXT NULL, "    //tên cho tài khoản email (Không bắt buộc)
                    + "email TEXT NOT NULL, " //địa chỉ tài khoản email
                    + "password TEXT NOT NULL, " //mật khẩu
                    + "type TEXT NOT NULL, " //loại (imap hay pop3) incoming messeage
                    + "server TEXT NOT NULL, " //gmail, outlook và yahoo (hiện tại thế này đã)
                    + "smtp TEXT NOT NULL,"   //smtp server của email outgoing messeage
                    + "portTLS TEXT NOT NULL," //port của stmp server
                    + "portSSL TEXT NOT NULL )");   //port của pop3 server (pop3 phổ biến hơn)
        } catch (SQLException ex) {
            //Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            //bỏ qua cái exception này nếu bảng tồn tại thôi          
        }
    }
    
    private void enableFunction() {
        composeMail.setEnabled(true);
        inboxMail.setEnabled(true);
        importantMail.setEnabled(true);
        sentMail.setEnabled(true);
        spamMail.setEnabled(true);
        trashMail.setEnabled(true);
        deleteMail.setEnabled(true);
        replyMail.setEnabled(true);
        forwardMail.setEnabled(true);
    }
    
    private void disableFunction() {
        composeMail.setEnabled(false);
        inboxMail.setEnabled(false);
        importantMail.setEnabled(false);
        sentMail.setEnabled(false);
        spamMail.setEnabled(false);
        trashMail.setEnabled(false);
        deleteMail.setEnabled(false);
        replyMail.setEnabled(false);
        forwardMail.setEnabled(false);
    }
    
    private void loadEmailList() {
        try {
            ps = connection.prepareStatement("SELECT email FROM email");
            rs = ps.executeQuery();
            while (rs.next()) {
               String email = rs.getString("email");
               emailList.addItem(email);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        composeMail = new javax.swing.JButton();
        importantMail = new javax.swing.JButton();
        sentMail = new javax.swing.JButton();
        spamMail = new javax.swing.JButton();
        inboxMail = new javax.swing.JButton();
        trashMail = new javax.swing.JButton();
        refreshAccount = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mailList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mailMesseage = new javax.swing.JTextArea();
        MailSearchInput = new javax.swing.JTextField();
        deleteMail = new javax.swing.JButton();
        replyMail = new javax.swing.JButton();
        forwardMail = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CheckNetwork = new javax.swing.JMenuItem();
        accountManage = new javax.swing.JMenuItem();
        closeMenu = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        aboutSoftware = new javax.swing.JMenuItem();
        aboutTeam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Email Client Manage");
        setIconImage(getIconImage());

        emailList.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        emailList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn tài khoản" }));
        emailList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-email-64.png"))); // NOI18N

        composeMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        composeMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-writer-50.png"))); // NOI18N
        composeMail.setText(" Soạn thư");
        composeMail.setToolTipText("Soạn thư mới");
        composeMail.setBorderPainted(false);
        composeMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        composeMail.setMargin(new java.awt.Insets(2, -6, 2, 14));
        composeMail.setPreferredSize(new java.awt.Dimension(180, 70));
        composeMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composeMailActionPerformed(evt);
            }
        });

        importantMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        importantMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-important-50.png"))); // NOI18N
        importantMail.setText("   Quan trọng");
        importantMail.setToolTipText("Các thư đánh nhãn quan trọng");
        importantMail.setBorderPainted(false);
        importantMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        importantMail.setIconTextGap(-8);
        importantMail.setMargin(new java.awt.Insets(2, -2, 2, 14));
        importantMail.setPreferredSize(new java.awt.Dimension(180, 70));

        sentMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        sentMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sent-50.png"))); // NOI18N
        sentMail.setText("   Đã gửi");
        sentMail.setToolTipText("Các thư đã gửi đi");
        sentMail.setBorderPainted(false);
        sentMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sentMail.setIconTextGap(-8);
        sentMail.setMargin(new java.awt.Insets(2, -2, 2, 14));

        spamMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        spamMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-spam-can-40.png"))); // NOI18N
        spamMail.setText("  Thư rác (spam)");
        spamMail.setToolTipText("Cẩn thận với thư lừa đảo");
        spamMail.setBorderPainted(false);
        spamMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spamMail.setMargin(new java.awt.Insets(2, 0, 2, 14));

        inboxMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        inboxMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-inbox-50.png"))); // NOI18N
        inboxMail.setText("   Hộp thư đến");
        inboxMail.setToolTipText("Mở hộp thư đến");
        inboxMail.setBorderPainted(false);
        inboxMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inboxMail.setIconTextGap(-8);
        inboxMail.setMargin(new java.awt.Insets(2, -4, 2, 14));
        inboxMail.setPreferredSize(new java.awt.Dimension(180, 70));

        trashMail.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        trashMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-trash-40.png"))); // NOI18N
        trashMail.setText(" Thùng rác");
        trashMail.setToolTipText("Các thư đã xóa lưu ở đây");
        trashMail.setBorderPainted(false);
        trashMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        trashMail.setMargin(new java.awt.Insets(2, 0, 2, 14));

        refreshAccount.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        refreshAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-refresh-30.png"))); // NOI18N
        refreshAccount.setText(" Làm mới");
        refreshAccount.setToolTipText("Làm mới danh sách tài khoản");
        refreshAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        refreshAccount.setMargin(new java.awt.Insets(2, 4, 2, 14));
        refreshAccount.setMaximumSize(new java.awt.Dimension(155, 59));
        refreshAccount.setMinimumSize(new java.awt.Dimension(155, 59));

        username.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Email Manger");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(emailList, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refreshAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inboxMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(composeMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importantMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sentMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spamMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(trashMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(composeMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(inboxMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(importantMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(sentMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spamMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trashMail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        mailList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Người gửi", "Tiêu đề", "Ngày gửi"
            }
        ));
        jScrollPane1.setViewportView(mailList);

        mailMesseage.setColumns(20);
        mailMesseage.setRows(5);
        jScrollPane2.setViewportView(mailMesseage);

        MailSearchInput.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        MailSearchInput.setToolTipText("Nhập thư cần tìm");

        deleteMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-32.png"))); // NOI18N
        deleteMail.setText("Xóa thư");
        deleteMail.setToolTipText("Xóa thư");
        deleteMail.setBorderPainted(false);
        deleteMail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteMail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        replyMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-reply-32.png"))); // NOI18N
        replyMail.setText("Trả lời thư");
        replyMail.setToolTipText("Trả lời thư");
        replyMail.setBorderPainted(false);
        replyMail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        replyMail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        forwardMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-forward-32.png"))); // NOI18N
        forwardMail.setText("Chuyển tiếp");
        forwardMail.setToolTipText("Chuyển tiếp thư");
        forwardMail.setBorderPainted(false);
        forwardMail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        forwardMail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Từ");

        jTextField2.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jTextField2.setToolTipText("Người gửi");

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tới");

        jTextField3.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jTextField3.setToolTipText("Người nhận");

        jTextField4.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jTextField4.setToolTipText("Ngày gửi thư");

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày gửi");

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tiêu đề");

        jTextField5.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jTextField5.setToolTipText("Tiêu đề thư");

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nội dung");

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jLabel8.setText("Nhập để tìm kiếm thư");

        jMenu1.setText("File");

        CheckNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-internet-30.png"))); // NOI18N
        CheckNetwork.setText("Kiểm tra kết nối");
        CheckNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckNetworkActionPerformed(evt);
            }
        });
        jMenu1.add(CheckNetwork);

        accountManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-users-settings-30.png"))); // NOI18N
        accountManage.setText("Quản lý tài khoản");
        accountManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountManageActionPerformed(evt);
            }
        });
        jMenu1.add(accountManage);

        closeMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        closeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-exit-30.png"))); // NOI18N
        closeMenu.setText("Thoát");
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenu);

        jMenuBar1.add(jMenu1);

        Help.setText("About");

        aboutSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-software-30.png"))); // NOI18N
        aboutSoftware.setText("Về phần mềm");
        Help.add(aboutSoftware);

        aboutTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-team-30.png"))); // NOI18N
        aboutTeam.setText("Về nhóm");
        Help.add(aboutTeam);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(MailSearchInput))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteMail)
                                .addGap(18, 18, 18)
                                .addComponent(replyMail)
                                .addGap(18, 18, 18)
                                .addComponent(forwardMail))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(replyMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forwardMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MailSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1)))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckNetworkActionPerformed
        // TODO add your handling code here:
        //kiểm tra kết nối Internet
        NetworkNotify.NotifyMesseage();
        
    }//GEN-LAST:event_CheckNetworkActionPerformed

    private void emailListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailListActionPerformed
        // TODO add your handling code here:
        if (emailList.getSelectedItem() == "Chọn tài khoản") { //nếu danh sách emailList ở chọn tài khoản
            //vô hiệu hóa tất cả chức năng tại màn hình chính
            disableFunction();
            username.setText("Email Manager");
        }
        else {
            //mở khóa lại toàn bộ chức năng
            enableFunction();
            try {
            //trước tiên chúng ta sẽ đổi Email Client thành tên của tk email
            ps = connection.prepareStatement("SELECT name FROM email WHERE email = ?");
            ps.setString(1, emailList.getSelectedItem().toString());
            rs = ps.executeQuery();

            while (rs.next()) {
                username.setText(rs.getString("name"));
            }

            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
            //mặc định sẽ feed "Hộp thư đến của tài khoản
        }
        
        
    }//GEN-LAST:event_emailListActionPerformed

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMenuActionPerformed

    private void accountManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountManageActionPerformed
        // TODO add your handling code here:
        frameManageAccount.callframe();
    }//GEN-LAST:event_accountManageActionPerformed

    private void composeMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeMailActionPerformed
        // TODO add your handling code here:
        //gọi frame soạn thư. Hết
        frameSendEmail.callframe();
    }//GEN-LAST:event_composeMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlaLaf Light */
        //theme này đẹp hơn nhiều
        LookandFeel.setTheme();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            HomePage home = new HomePage();
            home.setVisible(true);
            
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CheckNetwork;
    private javax.swing.JMenu Help;
    private javax.swing.JTextField MailSearchInput;
    private javax.swing.JMenuItem aboutSoftware;
    private javax.swing.JMenuItem aboutTeam;
    private javax.swing.JMenuItem accountManage;
    private javax.swing.JMenuItem closeMenu;
    private javax.swing.JButton composeMail;
    private javax.swing.JButton deleteMail;
    private javax.swing.JComboBox<String> emailList;
    private javax.swing.JButton forwardMail;
    private javax.swing.JButton importantMail;
    private javax.swing.JButton inboxMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable mailList;
    private javax.swing.JTextArea mailMesseage;
    private javax.swing.JButton refreshAccount;
    private javax.swing.JButton replyMail;
    private javax.swing.JButton sentMail;
    private javax.swing.JButton spamMail;
    private javax.swing.JButton trashMail;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
